version: "3"

volumes:
  buy_sell_db:

services:
  buy_sell_server:
    build: server/
    restart: always
    volumes:
      - buy_sell_db:/usr/src/app/server/db
      - buy_sell_db:/usr/src/app/server/static/img
    ports:
      - 80:5055

  alice:
    build: alice/
    restart: always
    ports:
      - 5057:5057

